org: andydevs
app: beneficial-serverlessapp
service: main
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
functions:
  hello:
    handler: handler.getname
    events:
      - http: GET /
